config/routes.rb
Rails.application.routes.draw do

  get 'home/index', as: :home

  root 'home#index'

  get 'slack-connection', to: 'slack_connection#show'

  #routes for weather refresh API button
  get 'weather/request', to: 'weather#weather_request', as: :weather_request

  #routes for weather chart
  get 'weather/chart_request', to: 'weather#weather_chart_request', as: :weather_chart

  #routes for cv card
  get 'cv_card/new', to: 'cv_cards#new'

  post 'cv_card/create', to: 'cv_cards#create'

  delete 'cv_cards/:id', to: 'cv_cards#destroy', as: :cv_card_destroy

  #routes for competence card

  get 'cv_competence/new', to: 'cv_competences#new'

  post 'cv_competence/create', to: 'cv_competences#create'

  delete 'cv_competence/:id', to: 'cv_competences#destroy', as: :cv_competence_destroy

  #routes for Formation Cards

  get 'formation/new', to: 'formations#new'

  post 'formation/create', to: 'formations#create'

  delete 'formation/:id', to: 'formations#destroy', as: :formation_destroy


  #routes for contact admin reply
  post 'contacts/:id', to: 'admin_reply#create'

  #Routes to destroy contact
  delete 'contacts/:id', to: 'contacts#destroy', as: :contact_destroy

  #Routes for slack reply messages
  post 'slack/reply', to: 'slack_command#reply'

  #routes for slack modals
  post 'slack/open-modal', to: 'slack_modal#handle_slack_interaction'

  devise_for :users

  #routes for ChatRoom
  delete 'rooms/:id', to: 'rooms#destroy', as: :rooms_destroy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :contacts do
    resources :admin_reply

  end

  resources :cv_cards
  resources :cv_competences
  resources :formations

  #rooting for ChatRoom

  resources :room_messages
  resources :rooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_and_belongs_to_many :rooms, join_table: :private_users_rooms

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up

  # def new
  #   super
  # end


  # POST /resource
  # def create
    #  super
    #end

  # GET /resource/edit
  #def edit
  # super
  #end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     home_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #
  #



end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%#- if controller_name != 'sessions' %>
<!--  <%#= link_to "Log in", new_session_path(resource_name) %><br />-->
<%# end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
 <small><%= link_to "Forgot your password?", new_password_path(resource_name) %><br /></small>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <small><%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br /></small>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
 <small><%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br /></small>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/shared/_login_form.html.erb
    <div class="login-card-body">
      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="form-group">
          <%= f.label :email %><br/>
          <%= f.email_field :email, autofocus: true, autocomplete: "username", class: "form-control", placeholder: "Enter email" %>
        </div>

        <div class="form-group">
          <%= f.label :password %><br/>
          <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Enter password" %>
        </div>

        <% if devise_mapping.rememberable? %>
          <div class="form-check">
            <%= f.check_box :remember_me, class: "form-check-input" %>
            <%= f.label :remember_me, class: "form-check-label" %>
          </div>
        <% end %>

        <div class="actions sign-up-button">
          <%= f.submit "Log in", class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= render "users/shared/links" %>
    </div>