config/routes.rb
Rails.application.routes.draw do

  get 'home/index', as: :home

  root 'home#index'

  get 'slack-connection', to: 'slack_connection#show'

  #routes for weather refresh API button
  get 'weather/request', to: 'weather#weather_request', as: :weather_request

  #routes for weather chart
  get 'weather/chart_request', to: 'weather#weather_chart_request', as: :weather_chart

  #routes for cv card
  get 'cv_card/new', to: 'cv_cards#new'

  post 'cv_card/create', to: 'cv_cards#create'

  delete 'cv_cards/:id', to: 'cv_cards#destroy', as: :cv_card_destroy

  #routes for competence card

  get 'cv_competence/new', to: 'cv_competences#new'

  post 'cv_competence/create', to: 'cv_competences#create'

  delete 'cv_competence/:id', to: 'cv_competences#destroy', as: :cv_competence_destroy

  #routes for Formation Cards

  get 'formation/new', to: 'formations#new'

  post 'formation/create', to: 'formations#create'

  delete 'formation/:id', to: 'formations#destroy', as: :formation_destroy


  #routes for contact admin reply
  post 'contacts/:id', to: 'admin_reply#create'

  #Routes to destroy contact
  delete 'contacts/:id', to: 'contacts#destroy', as: :contact_destroy

  #Routes for slack reply messages
  post 'slack/reply', to: 'slack_command#reply'

  #routes for slack modals
  post 'slack/open-modal', to: 'slack_modal#handle_slack_interaction'

  devise_for :users

  #routes for ChatRoom
  delete 'rooms/:id', to: 'rooms#destroy', as: :rooms_destroy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :contacts do
    resources :admin_reply

  end

  resources :cv_cards
  resources :cv_competences
  resources :formations

  #rooting for ChatRoom

  resources :room_messages
  resources :rooms

end

app/models/admin_reply.rb
class AdminReply < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one :admin_reply, dependent: :destroy
  validates :message, presence: true,
            length: {minimum: 10}

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/cv_card.rb
class CvCard < ApplicationRecord
  has_rich_text :content
end

app/models/cv_competence.rb
class CvCompetence < ApplicationRecord
  has_rich_text :content
end

app/models/formation.rb
class Formation < ApplicationRecord
  has_rich_text :content
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :private_users_rooms
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_and_belongs_to_many :rooms, join_table: :private_users_rooms

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
end

app/models/weather.rb
class Weather < ApplicationRecord

  # def humidity
  #   "#{self[:humidity]}%"
  # end

  # def temperature
  #   "#{self[:temperature]}°c"
  # end
end

app/controllers/cv_competences_controller.rb
class CvCompetencesController < ApplicationController

  def index
    @cv_competences = CvCompetence.all.order(:id)
  end

  def show
    @cv_competence = CvCompetence.find(params[:id])
  end

  def edit
    @cv_competence = CvCompetence.find(params[:id])
  end

  def new
    @cv_competence = CvCompetence.new
  end

  def create
    @cv_competence = CvCompetence.new(cv_competence_params)
    if @cv_competence.save

      redirect_to @cv_competence, notice: "Your new #{@cv_competence.title} has been created successfully"
    else
      render 'new'
    end
  end

  def update
    @cv_competence = CvCompetence.find(params[:id])

    if @cv_competence.update(cv_competence_params)
      redirect_to @cv_competence, notice: "Your new #{@cv_competence.title} has been updated successfully"
    else
      render 'edit'
    end
  end

  def destroy
    CvCompetence.find(params[:id]).destroy
    redirect_to cv_competences_path, notice: "Your CV competence has been deleted successfully"
  end

  def info_required?(info_number)
    info_number == "one"
  end

  helper_method :info_required?

end

private

def cv_competence_params
  params.require(:cv_competence).permit(:title, :content)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :verify_authenticity_token

  def index
    @cv_cards = CvCard.all
    @cv_competences = CvCompetence.all
    @formations = Formation.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def weather
    WeatherService.get_last_weather
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_cards_helper.rb
module CvCardsHelper
end

app/helpers/cv_competences_helper.rb
module CvCompetencesHelper
end

app/helpers/formation_helper.rb
module FormationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/response_helper.rb
module ResponseHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

  def dispatch_rooms
    Room.includes(:users).where(users: {id: nil}).or(
        Room.includes(:users).where(users: {id: current_user.id})
    )
  end

end

app/helpers/slack_modal_helper.rb
module SlackModalHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/cv_competences/edit.html.erb
<h1>Edit a competence</h1>
<%= form_with(model: @cv_competence, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, autofocus: true, autocomplete: "title", class: "form-control", required: true %>
  </div>

  <%= render partial: 'shared/active_form', locals: {form: form} %>

  <div class="submit">
    <%= form.submit "Submit", class: "btn btn-sm btn-outline-secondary" %>
  </div>

<% end %>

app/views/cv_competences/index.html.erb
<div class="row cv-show">
<%= render partial: 'shared/cv_competence', collection: @cv_competences %>
</div>

app/views/cv_competences/new.html.erb
<h1>Add a new competence</h1>
<%= form_with(scope: :cv_competence, url: cv_competence_create_path, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, autofocus: true, autocomplete: "title", class: "form-control", required: true %>
  </div>

  <%= render partial: 'shared/active_form', locals: {form: form} %>

  <div class="submit">
    <%= form.submit "Submit", class: "btn btn-sm btn-outline-secondary" %>
  </div>
<% end %>

app/views/cv_competences/show.html.erb
<h2><i class="fas fa-newspaper" class="table-dark"> <%= @cv_competence.title %>'s card </i></h2>


<%= render partial: 'shared/cv_competence', locals: {cv_competence: @cv_competence} %>


<%= render partial: "shared/delete_modal", locals: {link_to_delete: url_for(cv_competence_destroy_path(@cv_competence)), object_to_delete: @cv_competence} %>