config/routes.rb
Rails.application.routes.draw do

  get 'home/index', as: :home

  root 'home#index'

  get 'slack-connection', to: 'slack_connection#show'

  #routes for weather refresh API button
  get 'weather/request', to: 'weather#weather_request', as: :weather_request

  #routes for weather chart
  get 'weather/chart_request', to: 'weather#weather_chart_request', as: :weather_chart

  #routes for cv card
  get 'cv_card/new', to: 'cv_cards#new'

  post 'cv_card/create', to: 'cv_cards#create'

  delete 'cv_cards/:id', to: 'cv_cards#destroy', as: :cv_card_destroy

  #routes for competence card

  get 'cv_competence/new', to: 'cv_competences#new'

  post 'cv_competence/create', to: 'cv_competences#create'

  delete 'cv_competence/:id', to: 'cv_competences#destroy', as: :cv_competence_destroy

  #routes for Formation Cards

  get 'formation/new', to: 'formations#new'

  post 'formation/create', to: 'formations#create'

  delete 'formation/:id', to: 'formations#destroy', as: :formation_destroy


  #routes for contact admin reply
  post 'contacts/:id', to: 'admin_reply#create'

  #Routes to destroy contact
  delete 'contacts/:id', to: 'contacts#destroy', as: :contact_destroy

  #Routes for slack reply messages
  post 'slack/reply', to: 'slack_command#reply'

  #routes for slack modals
  post 'slack/open-modal', to: 'slack_modal#handle_slack_interaction'

  devise_for :users

  #routes for ChatRoom
  delete 'rooms/:id', to: 'rooms#destroy', as: :rooms_destroy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :contacts do
    resources :admin_reply

  end

  resources :cv_cards
  resources :cv_competences
  resources :formations

  #rooting for ChatRoom

  resources :room_messages
  resources :rooms

end

app/models/admin_reply.rb
class AdminReply < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one :admin_reply, dependent: :destroy
  validates :message, presence: true,
            length: {minimum: 10}

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/cv_card.rb
class CvCard < ApplicationRecord
  has_rich_text :content
end

app/models/cv_competence.rb
class CvCompetence < ApplicationRecord
  has_rich_text :content
end

app/models/formation.rb
class Formation < ApplicationRecord
  has_rich_text :content
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :private_users_rooms
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_and_belongs_to_many :rooms, join_table: :private_users_rooms

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
end

app/models/weather.rb
class Weather < ApplicationRecord

  # def humidity
  #   "#{self[:humidity]}%"
  # end

  # def temperature
  #   "#{self[:temperature]}°c"
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def weather
    WeatherService.get_last_weather
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_cards_helper.rb
module CvCardsHelper
end

app/helpers/formation_helper.rb
module FormationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/response_helper.rb
module ResponseHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

  def dispatch_rooms
    Room.includes(:users).where(users: {id: nil}).or(
        Room.includes(:users).where(users: {id: current_user.id})
    )
  end

end

app/helpers/slack_modal_helper.rb
module SlackModalHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalPage</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body class="background-color">
<%= render "shared/navbar" %>
<%= render partial: "shared/toast" %>
<div id="page-container" class="container">
  <%= yield %>

</div>
<%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_accordion_cv_cards.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-outline-secondary btn-lg btn-block" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          My personal experiences
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="row">
        <%= render partial: 'shared/cv_card', collection: @cv_cards %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_accordion_formation.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-dark btn-lg btn-block" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          My formations
        </button>
      </h2>
    </div>

    <div id="collapseTwo" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="row">
        <%= render partial: 'shared/formation', collection: @formations %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_chatroom_template.html.erb
<div class="chat-message-container">
      <div class="username" data-role="user-username"> <%= chatroom_template[:user] unless chatroom_template.nil? %></div>
  <div class="row no-gutters">
    <div class="col-auto text-center">
    </div>
    <div class="col">
      <div class="message-content">
        <p class="mb-1" data-role="message-text"> <%= chatroom_template[:message] unless chatroom_template.nil?%></p>
        <div class="text-right">
          <small data-role="message-date"><%= chatroom_template[:message_date] unless chatroom_template.nil? %></small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cv_competence.html.erb
<ul class="list-group list-group-flush col-md-6 col-sm-12 cv-background">
  <li class="list-group-item cv-title"><%= cv_competence.title %></li>

  <li class="list-group-item text-comp-style card-border">
    <ul>
      <%= cv_competence.content %>
    </ul>
  </li>
  <% if !current_user.nil? && current_user.admin %>
    <li class="list-group-item cv-button ">
      <div class="text-style">
        <a href="<%= cv_competence_path(cv_competence) %>"><i class="far fa-eye"></i></a>
        <a href="<%= edit_cv_competence_path(cv_competence) %>"><i class="fas fa-edit"></i></a>
        <a type="button" data-toggle="modal" data-target="#deleteModal<%= cv_competence.id %>">
          <i class="far fa-trash-alt"></i></a>
  </div>
  </li>
  <% end %>
</ul>
<%= render partial: "shared/delete_modal", locals: {link_to_delete: url_for(cv_competence_destroy_path(cv_competence)), object_to_delete: cv_competence} %>

app/views/shared/_cv_competence_new.html.erb
<% if current_user != nil and current_user.admin %>
  <%= link_to 'new cv competence', {controller: '/cv_competences', action: 'new'}, class: "btn btn-outline-secondary" %>
<% end %>

app/views/shared/_cv_edit.html.erb
<% if current_user != nil and current_user.admin %>
  <%= link_to 'new cv', {controller: '/cv_cards', action: 'new'}, class: "btn btn-outline-secondary" %>
<% end %>

<!--si 'current_user n'est pas NIl, ET s'il nest pas 'admin'
 ne pas afficher le boutton -->

app/views/shared/_delete_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="deleteModal<%= object_to_delete.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">delete confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        vous êtes sur le point de supprimer <%= object_to_delete.class %> avec l'id <%= object_to_delete.id %>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="<%= link_to_delete %>" class="btn btn-outline-danger" data-method="delete">Delete</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_login_modal.html.erb
<!-- LOGIN Modal -->

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "users/shared/login_form" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-1">
      <h4 class="text-white">
        <div class="navbar">
          <div class="navbar-buttons">
              <%= render 'shared/navbar_buttons' %>
          </div>
          <div class="navbar-weather">
            <i class="fas fa-cloud-sun"></i>
            <div class="badge badge-dark" id="weather_city"><%= weather.city %></div>
            <div class="badge badge-dark" id="weather_temperature"><%= weather.temperature %>°c</div>
            <div class="badge badge-dark" id="weather_humidity"><%= weather.humidity %>%</div>
            <div class="badge badge-dark" id="weather_description"><%= weather.description %></div>
            <button class="btn btn-sm btn-outline-light" id="weather_button" data-link="<%= weather_request_path %>">
              refresh
            </button>
            <button type="button" class="btn btn-sm btn-outline-light" data-toggle="modal" data-target="#exampleModal">
              weather history
            </button>
          </div>
          <div class="navbar-login">
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-light") %>
              <%= link_to('Edit registration', edit_user_registration_path, class: "btn btn-outline-light") %>
            <% else %>
              <%= link_to('Login', new_user_session_path, class: "btn btn-outline-light", "data-toggle": "modal", "data-target": "#exampleModalCenter") %>
              <%= link_to('Register', new_user_registration_path, class: "btn btn-outline-light") %>
            <% end %>
            <%= render "shared/cv_edit" %>
            <%= render "shared/cv_competence_new" %>
            <%= render "shared/formation_new" %>

          </div>
        </div>
      </h4>
    </div>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark" style="background-color: #212121;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

<%= render "shared/login_modal" %>
<%= render "shared/weather_modal" %>

app/views/shared/_navbar_buttons.html.erb
  <%= link_to 'Home', home_path, class: "btn btn-outline-light" %>
<% if user_signed_in? %>
  <%= link_to 'My contacts', contacts_path, class: "btn btn-outline-light" %>
  <%= link_to 'My cv', cv_cards_path, class: "btn btn-outline-light" %>
  <%= link_to 'My competences', cv_competences_path, class: "btn btn-outline-light" %>
  <%= link_to 'My chat', rooms_path, class: "btn btn-outline-light" %>
  <%= link_to 'My Formations', formations_path, class: "btn btn-outline-light" %>
<% end %>

app/views/shared/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-outline-secondary' do %>
    Create a new room
  <% end %>
</div>

<% if dispatch_rooms.present?%>
  <nav class="nav flex-column">
    <% dispatch_rooms.each do |room| %>
      <div class="room-name">
        <%= link_to room.name, room_path(room), class: 'btn btn-light' %>
        <div type="button" data-toggle="modal" data-target="#deleteModal<%= room.id %>" class=" btn btn-light btn-sm">
          <i class="far fa-trash-alt"></i></div>
      </div>
      <%= render partial: "shared/delete_modal", locals: {link_to_delete: url_for(rooms_destroy_path(room)), object_to_delete: room} %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

<%= render partial: 'shared/connected_users' %>

app/views/shared/_shared_buttons.html.erb
<%#= link_to 'Home', home_path, class: "btn-sm btn-outline-secondary" %>
<% if user_signed_in? %>
  <%#= link_to 'Back', :back, class: "btn-sm btn-outline-secondary" %>
  <%#= link_to 'My contacts', contacts_path, class: "btn-sm btn-outline-secondary" %>
  <%#= link_to 'My cv', cv_cards_path, class: "btn-sm btn-outline-secondary" %>
  <%#= link_to 'My competences', cv_competences_path, class: "btn-sm btn-outline-secondary" %>
  <%#= link_to 'My chat', rooms_path, class: "btn-sm btn-outline-secondary" %>
<% end %>
<div class="font-icons">
  <a href="https://github.com/Jean-Berti/personal-page" target="_blank">
    <i class="fab fa-github fa-2x"></i></a>

  <a href="https://linkedin.com/in/jean-berti-azar" target="_blank">
    <i class="fab fa-linkedin fa-2x"></i></a>
</div>

app/views/shared/_toast_template.html.erb
<div aria-live="polite" aria-atomic="true" class="flash" style="height: 100px;">
  <div class="toast <%= flash_name %> " role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
    <div class="toast-header">
      <strong class="mr-auto">Alert</strong>
      <small class="text-muted toast-flash-time"> <%= flash_time %></small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body toast-flash-message">
      <%= flash_message %>
    </div>
  </div>
</div>

app/views/shared/_weather_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Weather graphic</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="myChart"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>